### ISSUE TITLE
Run Application On Startup

### ISSUE THREAD

**Issue by alexanderepstein** [alexanderepstein/Sandman#10]
Possibly implement this 
https://github.com/Teamwork/node-auto-launch
Only downside is after removing my program the files created by the auto launch will still be present.

**Comment by alexanderepstein** [comment]
Not worth it because of issue as stated above

**Comment by luchillo17** [comment]
Actually the package mentioned tells you which files will be left behind, you can configure the Electron uninstaller to just remove such files, not that many, just need to keep in mind the OS in which you're when uninstalling.

**Comment by alexanderepstein** [comment]
@luchillo17 Although it does mention it I do not have the ability to configure my uninstaller as far as I know. On windows you just remove my project folder, on mac you just get rid of the app, only on debian and redhat linux is where you actually remove it through the package manager since it was installed through it. Essentially what I'm trying to say is on Mac & Windows the user is just deleting my files thats not much of an uninstall and i cant expect the user to find hidden files and the other tricks auto launch uses to start. Additionally it doesn't seem to be able to set up easily with a preference so if its not desired by the user it would be forced upon them

**Comment by luchillo17** [comment]
Oh i see, you don't have an installer nor uninstaller pipeline with your electron app.
