### ISSUE TITLE
Sleep Tracking

### ISSUE THREAD

**Issue by alexanderepstein** [alexanderepstein/Sandman#15]
I think insomnia has the potential to be a decent sleep tracking application with quick modal questions to generate data and visualize this data onto plots. This data can then be used to help better regulate your sleep cycles by changing the algorithm that tells you when to go to bed.

**Comment by zomars** [comment]
I use an app called Sleep Cycle for sleep monitoring, it uses the microphone and generates all this kind of data. Maybe you could get some inspiration from it or make it compatible. Nice work so far BTW.
