### ISSUE TITLE
Bright blue background

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [alexanderepstein/Sandman#37]
**Issue Label:** Bug

**Description of bug or feature enhancement:**
Viewing blue light at night [is harmful](http://www.health.harvard.edu/staying-healthy/blue-light-has-a-dark-side). Please change the background color of the app to something a bit less jarring.

**OS and OS version:**
Any

**Version of Insomnia Application:**
Any current

**Comment by alexanderepstein** [comment]
I was planning on throwing in a dark theme option. I totally agree the color scheme goes against the purpose of the application. Hopefully this will come with the next release.

**Comment by alexanderepstein** [comment]
@priscilamtzfraire could you please help me out in designing a darker U.I. I decided instead of making it an option it would just make sense if the entire application was darker. I tried to do this by editing the color values in main.css but I couldn't come up with a blend of colors that actually harmonized like you did.

**Comment by priscilamtzfraire** [comment]
Sure @alexanderepstein I'll be working on it and I'll share some screenshots with you guys, so I can receive some feedback :)

**Comment by alexanderepstein** [comment]
@priscilamtzfraire awesome thanks so much if it helps in designing accent colors the there will be a new logo instead of the three z's it can be found here https://www.shareicon.net/data/128x128/2016/04/22/753637_wizard_512x512.png

**Comment by alexanderepstein** [comment]
@priscilamtzfraire The logo change comes with the fact I am changing the name of this project to Sandman so that it is unique. I am planning on changing the name with the release of the darker U.I.

**Comment by alexanderepstein** [comment]
@priscilamtzfraire Even though its the same version number it is a new design that is up right now as I officially changed the name, please look at the new color scheme and make it better than it is now. I can tell i didn't get it 100% right and am trying to perfect the look before i continue adding to the functionality

**Comment by priscilamtzfraire** [comment]
@alexanderepstein Got it :) Let me see what I can do, but you did a pretty good job! 👍

**Comment by priscilamtzfraire** [comment]
@alexanderepstein I updated some colors using a darkened or lightened version of the base color you used as the background (#622569). Please let me know your comments :)

**Comment by alexanderepstein** [comment]
@priscilamtzfraire I love it the accents you picked for colors look really good, about to merge over to master and set up a new release 👍
