### ISSUE TITLE
Optimal Sleeping Times not displaying properly

### ISSUE THREAD

**Issue by ballek** [alexanderepstein/Sandman#42]
**Issue Label:**
* [x ] bug
* [ ] feature
* [ ] enhancement

**Description of bug or feature enhancement:**
Times are listed in the dreaded NaaN
<img width="565" alt="screen shot 2017-08-04 at 1 49 15 pm" src="https://user-images.githubusercontent.com/7898004/28980453-c69a6f8e-791b-11e7-899a-a4c96cfcb2d0.png">

**OS and OS version:**
* [x ] Mac
* [ ] GNU Linux 32 Bit
* [ ] GNU Linux 64 Bit
* [ ] Redhat Linux
* [ ] Windows 64 Bit
* [ ] Windows 32 Bit

**Version of Sandman Application:** 1.9.2

**Comment by ballek** [comment]
@luchillo17 fixed it! Thank you!

**Comment by luchillo17** [comment]
Most likely a change on the way the app store the settings making the previous settings unreachable, at least is easy to fix if you know how.
